export const Days = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];

export const ScheduleData = {
  Mon: [
    { time: '12a', value: 25 },
    { time: '3a', value: 38 },
    { time: '6a', value: 78, mostActive: true },
    { time: '9a', value: 65 },
    { time: '12p', value: 40 },
    { time: '3p', value: 55 },
    { time: '6p', value: 72 },
    { time: '9p', value: 33 },
  ],
  Tue: [
    { time: '12a', value: 18 },
    { time: '3a', value: 29 },
    { time: '6a', value: 50 },
    { time: '9a', value: 85, mostActive: true },
    { time: '12p', value: 60 },
    { time: '3p', value: 45 },
    { time: '6p', value: 70 },
    { time: '9p', value: 41 },
  ],
  Wed: [
    { time: '12a', value: 22 },
    { time: '3a', value: 31 },
    { time: '6a', value: 45 },
    { time: '9a', value: 70 },
    { time: '12p', value: 92, mostActive: true },
    { time: '3p', value: 68 },
    { time: '6p', value: 81 },
    { time: '9p', value: 39 },
  ],
  Thu: [
    { time: '12a', value: 15 },
    { time: '3a', value: 24 },
    { time: '6a', value: 66 },
    { time: '9a', value: 77 },
    { time: '12p', value: 55 },
    { time: '3p', value: 88, mostActive: true },
    { time: '6p', value: 75 },
    { time: '9p', value: 48 },
  ],
  Fri: [
    { time: '12a', value: 30 },
    { time: '3a', value: 40 },
    { time: '6a', value: 50 },
    { time: '9a', value: 60 },
    { time: '12p', value: 70 },
    { time: '3p', value: 80 },
    { time: '6p', value: 95, mostActive: true },
    { time: '9p', value: 85 },
  ],
  Sat: [
    { time: '12a', value: 45 },
    { time: '3a', value: 35 },
    { time: '6a', value: 25 },
    { time: '9a', value: 55 },
    { time: '12p', value: 75 },
    { time: '3p', value: 98, mostActive: true },
    { time: '6p', value: 90 },
    { time: '9p', value: 65 },
  ],
  Sun: [
    { time: '12a', value: 50 },
    { time: '3a', value: 33 },
    { time: '6a', value: 20 },
    { time: '9a', value: 48 },
    { time: '12p', value: 82, mostActive: true },
    { time: '3p', value: 76 },
    { time: '6p', value: 60 },
    { time: '9p', value: 40 },
  ],
};